name: travelin_flutter_component
description: Components of Travelin App for Angkasa Pura II
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-VariableFont.ttf
  uses-material-design: true
  generate: true